<?php
$todos = $this->getData('guzzle');
?>


<?php include('tp4/app/templates/head.phtml'); ?>

<?php
    echo('<table class="styled-table">');

    echo '<tr>';
        echo "<th>userId</th>";
        echo "<th>TaskId</th>";
        echo "<th>title</th>";
        echo "<th>isDone</th>";
    echo "</tr>";

    foreach ($todos as $v) {
        echo ("<tr>");

        echo "<td>" . $v["userId"] . "</td>";
        echo "<td>" . $v["id"] . "</td>";
        echo "<td>" . $v["title"] . "</td>";
        if($v["completed"]) echo "<td>true</td>";
        else echo "<td>false</td>";

        echo "</tr>";
    }

    echo "</table>";
?>

<?php include('tp4/app/templates/footer.phtml'); ?>

<style>
    .styled-table {
        border-collapse: collapse;
        margin: 25px 0;
        font-size: 0.9em;
        font-family: sans-serif;
        min-width: 400px;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
    }
    .styled-table thead tr {
        background-color: #009879;
        color: #ffffff;
        text-align: left;
    }
    .styled-table th,
    .styled-table td {
        padding: 12px 15px;
    }
    .styled-table tbody tr {
        border-bottom: 1px solid #dddddd;
    }

    .styled-table tbody tr:nth-of-type(even) {
        background-color: #f3f3f3;
    }

    .styled-table tbody tr:last-of-type {
        border-bottom: 2px solid #009879;
    }
    .styled-table tbody tr.active-row {
        font-weight: bold;
        color: #009879;
    }

</style>