index:
    path: /
    controller: App\Controller\HomeController::home

matchs:
    path: /match
    controller: App\Controller\MatchController::home

connexion:
    path: /connexion
    controller: App\Controller\ConnexionController::login

inscription:
    path: /inscription
    controller: App\Controller\RegistrationController::register

info:
    path: /info
    controller: App\Controller\CompteInfoController::get_info

contact:
    path: /contact
    controller: App\Controller\ContactController::contact

classement:
    path: /classement
    controller: App\Controller\ClassementController::show_classement

insert_prono:
    path: /insert_prono
    controller: App\Controller\PronoController::index