#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
  path: /
  controller: App\Controller\HomeController::home

product:
  path: /product
  controller: App\Controller\ProductController::view

customer:
  path: /customer
  controller: App\Controller\CustomerController::view

productPage:
  path: /productInsert
  controller: App\Controller\InsertController::createProduct

CustomerPage:
  path: /customerInsert
  controller: App\Controller\InsertController::createCustomer